/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.embah

import app.embah.processing.RemappingResourceLoader
import java.io.File
import java.lang.invoke.MethodHandles
import java.net.URLClassLoader

class App {

    lateinit var classLoader: URLClassLoader

    fun run() {

        val separator = System.getProperty("file.separator")
        val directory = "${System.getProperty("user.home")}${separator}alora$separator"
        val remapper  = RemappingResourceLoader("${directory}client.jar").also {
            it.client.outputAsJar("src/main/resources/modified.jar")
        }

        //add libs to the classloader
        classLoader = URLClassLoader(arrayOf(
                //the game jar itself
                File("src/main/resources/modified.jar").toURI().toURL(),
                //the jna library
                File("${directory}jna-4.5.2.jar").toURI().toURL(),
                //the discord presence library
                File("${directory}discord-rpc-release-v3.3.0.jar").toURI().toURL(),
                //opengl client drawing libs
                File("${directory}clientlibs.jar").toURI().toURL()
        ))

        //Alora's main class is always 'Alora'
        val entrance = classLoader.loadClass("Alora")
        val main = entrance.getDeclaredMethod("main", Array<String>::class.java)
        MethodHandles.lookup().unreflect(main).invoke(*arrayOf("./") as Array<*>)
    }
}

fun main() {
    App().run()
}
